---
title: "Week10"
author: "Zeyao Li"
date: "3/25/2021"
output: html_document
---

\newpage

Week 10

(1) This study investigated whether the tendency of "even out" calls among college basketball referees exists in 2010. Meanwhile, analysis on whether referees with greater control for foul calls make more "even out" calls was also conducted. (2) The data was collected among the Big Ten, ACC, and Big East conference seasons during 2009-2010. (3) It included 340 games with 4972 fouls during the first half of each game. (4) The sources of the data are the three major basketball conferences mentioned above. The response variable, number of fouls, was recorded during each game. 

(5a) In order to find out how the difference of fouls between home and visiting teams and random effects affected whether home team receives the next foul call, a generalized linear mixed model with logit link was used. (5b) The model for $p_{i[gh]j}$ (the probability that in Game $i$, the $j^{th}$ foul was called on Home Team $h$ but not Visiting Team $g$) is presented below:

$$\log\bigg(\frac{p_{i[gh]j}}{1-p_{i[gh]j}}\bigg) = [\alpha_{0}+\beta_{0}\mathrm{foul.diff}_{ij}]+[u_{i}+v_{h}+w_{g}]$$
(5c) $\alpha_{0}$ is mean log odds of a home foul among all games and fouls; $\beta_{0}$ is the decrease in log odds of a home foul on average when there is one foul increase between number of fouls from home team and visiting team; $u_{i}$ is the random effect for games; $v_{h}$ is the random effect for home teams; $w_{g}$ is the random effect for visiting teams. 

Since number of fouls for a particular game, a home team, and a visiting team might have similar patterns, these three effects were included in the model as random effects. The difference between number of fouls of home team and visiting team is considered as a fixed effect. 


References:

Roback, P., & Legler, J. (2021). 11.2 Case Study: College Basketball Referees. In Beyond Multiple Linear Regression: Applied Generalized Linear Models and Multilevel Models in R (1. ed., pp. 374-400). Boca Raton: CRC Press.

Anderson, K. J., & Pierce, D. A. (2009). Officiating bias: the effect of foul differential on foul calls in NCAA basketball. J Sports Sci, 27(7), 687-694. doi:10.1080/02640410902729733
